### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by kuhanaklobasa** [ro-py/ro.py#62]
Improving the docs would improve developers workflow and code efficiency which would result in lower amount of requests aswell.

My suggestion on how to improve docs:
- Add ~40px space or a separator between each method so its visible what belongs where
- Remove unnecessary source code snippets and replace them with code examples (on the methods which might sound confusing)
- Remove unnecessary __init__ constructors found at some methods
- Make an examples tab

**Comment by jmkd3v** [comment]
> Add ~40px space or a separator between each method so its visible what belongs where

I don't have any plans to make any style changes to the docs - mkdocstrings controls that, not me.

> Remove unnecessary source code snippets and replace them with code examples (on the methods which might sound confusing)

I don't think it makes sense to put code examples inline in docstrings for methods. I instead would like to have individual articles that cover multiple methods, like "how to use thumbnails", instead of examples like "how to use ThumbnailProvider.blahblah".

> Remove unnecessary __init__ constructors found at some methods

I don't know what you mean by this - could you clarify?

> Make an examples tab

I will work on example articles in the future.
